/* lang_data.c - erzeugt von scripts/gen_sprache.py. Nicht von Hand
 * aendern, sondern data/sprache-en.txt und dann "make sprache". */

#include "retro.h"

const struct lang_entry {
    const char *de;
    const char *en;
} lang_table[] = {
    { "         daneben moeglich: %u MiB frei",
      "         alongside possible: %u MiB free" },
    { "  %-6s %s (%u MiB)",
      "  %-6s %s (%u MiB)" },
    { "  %2u  %s  (%u Treffer)",
      "  %2u  %s  (%u hits)" },
    { "  %d von 4 Antworten",
      "  %d of 4 answers" },
    { "  %u Eintraege",
      "  %u entries" },
    { "  %u Eintraege%s",
      "  %u entries%s" },
    { "  %u Eintraege, %u Bytes",
      "  %u entries, %u bytes" },
    { "  %u Fundstellen%s",
      "  %u hits%s" },
    { "  %u Sektoren zu %u Byte (%u MiB)",
      "  %u sectors of %u bytes (%u MiB)" },
    { "  %u Zeilen",
      "  %u lines" },
    { "  %u gefunden%s",
      "  %u found%s" },
    { "  %u offen von %u - %s",
      "  %u open of %u - %s" },
    { "  %u von %u Bytes",
      "  %u of %u bytes" },
    { "  %u von %u Zeilen",
      "  %u of %u lines" },
    { "  -  daneben",
      "  -  alongside" },
    { "  ... weitere Unterschiede",
      "  ... more differences" },
    { "  Ablage        %s - unter /Festplatte",
      "  Storage       %s - at /Festplatte" },
    { "  Ablage        : %u MiB ab Sektor %u",
      "  Storage       : %u MiB from sector %u" },
    { "  Antwort von %s: Zeit %u ms",
      "  Answer from %s: time %u ms" },
    { "  Arbeitsflaeche : %dx%d Punkte",
      "  Work area      : %dx%d points" },
    { "  Art       : %s%s",
      "  Kind      : %s%s" },
    { "  Auch als \"%s\"",
      "  Also as \"%s\"" },
    { "  Auch als \"%s\".",
      "  Also as \"%s\"." },
    { "  Auf dem Bus gefunden:",
      "  Found on the bus:" },
    { "  Bytes abgefragt : %u",
      "  Bytes polled    : %u" },
    { "  Bytes ueber IRQ : %u",
      "  Bytes via IRQ   : %u" },
    { "  Darf      : %s",
      "  May       : %s" },
    { "  Dateien       Dateisystem im Arbeitsspeicher",
      "  Files         file system in memory" },
    { "  Dateisystem : FAT32, %u Byte je Cluster",
      "  File system : FAT32, %u bytes per cluster" },
    { "  Die Aufloesung setzt der Bootloader; sie laesst sich hier nicht aendern.",
      "  The bootloader sets the resolution; it cannot be changed here." },
    { "  Durchgelassen: %u ein, %u aus; verworfen: %u ein, %u aus",
      "  Passed: %u in, %u out; dropped: %u in, %u out" },
    { "  EFI-Abschnitt : %u MiB ab Sektor %u",
      "  EFI partition : %u MiB from sector %u" },
    { "  Eintraege : %u",
      "  Entries   : %u" },
    { "  Empfangen        : %u Pakete, %u Byte",
      "  Received         : %u packets, %u bytes" },
    { "  Gateway          : %s",
      "  Gateway          : %s" },
    { "  Geaendert : %02u.%02u.%04u %02u:%02u",
      "  Changed   : %02u.%02u.%04u %02u:%02u" },
    { "  Gehoert   : %s:%s",
      "  Owner     : %s:%s" },
    { "  Gesendet         : %u Pakete, %u Byte",
      "  Sent             : %u packets, %u bytes" },
    { "  Grafik        linearer Framebuffer mit Backbuffer",
      "  Graphics      linear framebuffer with a back buffer" },
    { "  Groesse     : %s",
      "  Size        : %s" },
    { "  Groesse   : %s%s",
      "  Size      : %s%s" },
    { "  Grundeinstellung ausgehend: %s",
      "  Default outbound: %s" },
    { "  Grundeinstellung eingehend: %s",
      "  Default inbound:  %s" },
    { "  Gruppen   : %s",
      "  Groups    : %s" },
    { "  Hardware-Adresse : %s",
      "  Hardware address : %s" },
    { "  Heim      : %s",
      "  Home      : %s" },
    { "  IP-Adresse       : %s",
      "  IP address       : %s" },
    { "  Keine IP-Adresse (DHCP ohne Antwort).",
      "  No IP address (DHCP got no answer)." },
    { "  Keine Regeln - es gilt die Grundeinstellung.",
      "  No rules - the default applies." },
    { "  Kern %u",
      "  Core %u" },
    { "  Kernel        eigener 64-Bit-Kernel, Long Mode",
      "  Kernel        own 64-bit kernel, long mode" },
    { "  Liegt     : %s",
      "  Path      : %s" },
    { "  Mit den Pfeiltasten holt man sie zurueck.",
      "  The arrow keys bring them back." },
    { "  Namensserver     : %s",
      "  Name server      : %s" },
    { "  Netzmaske        : %s",
      "  Netmask          : %s" },
    { "  Nummer    : %u",
      "  Number    : %u" },
    { "  Oberflaeche   eigenes Fenstersystem",
      "  Interface     own window system" },
    { "  PS/2-Controller : da, Port 2 %s",
      "  PS/2 controller : present, port 2 %s" },
    { "  PS/2-Controller : keiner",
      "  PS/2 controller : none" },
    { "  PS/2-Maus       : %s",
      "  PS/2 mouse      : %s" },
    { "  Pakete verworfen: %u",
      "  Packets dropped : %u" },
    { "  Paketlaenge     : %u Byte",
      "  Packet length   : %u bytes" },
    { "  Rechte    : %s (%04o)",
      "  Mode      : %s (%04o)" },
    { "  Rolle     : %s",
      "  Role      : %s" },
    { "  SHA-256 ueber %u Bytes von %s",
      "  SHA-256 over %u bytes of %s" },
    { "  Speicher      Bitmap-Seitenverwaltung und Heap",
      "  Memory        bitmap page allocator and heap" },
    { "  Startbereich  %s - Bootloader und Kernel",
      "  Boot area     %s - bootloader and kernel" },
    { "  Startbereich  der vorhandene wird mitbenutzt",
      "  Boot area     the existing one is shared" },
    { "  Treiber       PS/2-Tastatur und -Maus, PIT, RTC",
      "  Drivers       PS/2 keyboard and mouse, PIT, RTC" },
    { "  USB-Maus        : %s",
      "  USB mouse       : %s" },
    { "  Verbindung       : %s",
      "  Link             : %s" },
    { "  Verbindung       : %s, %u MBit/s",
      "  Link             : %s, %u Mbit/s" },
    { "  Zeiger          : %d, %d",
      "  Pointer         : %d, %d" },
    { "  Zeitueberschreitung",
      "  Timed out" },
    { "  aufgaben neu <text> | fertig <n> | weg <n> | wichtig <n> <stufe> | termin <n> <datum>",
      "  aufgaben neu <text> | fertig <n> | weg <n> | wichtig <n> <level> | termin <n> <date>" },
    { "  belegt  : %u MiB",
      "  in use  : %u MiB" },
    { "  benutzer neu|loeschen|passwort|rolle|verwalter <name> [wert]",
      "  benutzer neu|loeschen|passwort|rolle|verwalter <name> [value]" },
    { "  benutzt    : %u KiB",
      "  used       : %u KiB" },
    { "  firewall an|aus | standard <richtung> <tat> | regel <richtung> <tat> <protokoll> <ziel> <ports> | weg <n> | leeren | speichern",
      "  firewall an|aus | standard <direction> <action> | regel <direction> <action> <protocol> <target> <ports> | weg <n> | leeren | speichern" },
    { "  frei        : %s",
      "  free        : %s" },
    { "  frei    : %u MiB",
      "  free    : %u MiB" },
    { "  gesamt  : %u MiB",
      "  total   : %u MiB" },
    { "  kaefig <profil> <programm> [text]",
      "  kaefig <profile> <program> [text]" },
    { "  pruefspur [alle|abgewiesen|speichern]",
      "  pruefspur [alle|abgewiesen|speichern]" },
    { "  reserviert : %u KiB",
      "  reserved   : %u KiB" },
    { "  z.B.  finde / *.txt",
      "  e.g.  finde / *.txt" },
    { "  z.B.  rechne (3 + 4) * 1024",
      "  e.g.  rechne (3 + 4) * 1024" },
    { "  z.B.  starte /Programme/hallo.elf",
      "  e.g.  starte /Programme/hallo.elf" },
    { " (abgefragt)",
      " (polled)" },
    { " (automatisch)",
      " (automatic)" },
    { " (geaendert)",
      " (modified)" },
    { " (unvollstaendig)",
      " (incomplete)" },
    { " - unvollstaendig!",
      " - incomplete!" },
    { "\"%s\" endgueltig geloescht",
      "\"%s\" deleted for good" },
    { "\"%s\" endgueltig loeschen? Das laesst sich nicht mehr zuruecknehmen.",
      "Delete \"%s\" for good? This cannot be undone." },
    { "\"%s\" in den Papierkorb legen?",
      "Move \"%s\" to the trash?" },
    { "\"%s\" ist weder Befehl noch Bereich.",
      "\"%s\" is neither a command nor a group." },
    { "\"%s\" ist weder Befehl noch Programm",
      "\"%s\" is neither a command nor a program" },
    { "\"%s\" ist wieder da.",
      "\"%s\" is back." },
    { "\"%s\" kennt die Konsole nicht.",
      "The console does not know \"%s\"." },
    { "\"%s\" kommt darin nicht vor.",
      "\"%s\" does not appear in it." },
    { "\"%s\" liegt im Papierkorb - \"papierkorb zurueck\" holt es wieder",
      "\"%s\" is in the trash - \"papierkorb zurueck\" brings it back" },
    { "\"%s\" liess sich nicht zurueckholen.",
      "\"%s\" could not be brought back." },
    { "\"hilfe <bereich>\" zeigt nur einen Teil, \"man <befehl>\" alles zu einem Befehl.",
      "\"hilfe <group>\" shows one part only, \"man <command>\" everything about a command." },
    { "\"hilfe\" zeigt alle Befehle.",
      "\"hilfe\" lists all commands." },
    { "%-5u %-6s %-16s %-10s %u KiB",
      "%-5u %-6s %-16s %-10s %u KiB" },
    { "%10s  insgesamt in %s",
      "%10s  in total in %s" },
    { "%d von %u Meldungen",
      "%d of %u messages" },
    { "%d von %u Meldungen - %u aeltere sind aus dem Ring gefallen",
      "%d of %u messages - %u older ones fell out of the ring" },
    { "%d, %u Byte, %s",
      "%d, %u bytes, %s" },
    { "%dx%d ging nicht",
      "%dx%d did not work" },
    { "%s\n%s, %s\nGehoert %s:%s - %s (%04o)",
      "%s\n%s, %s\nOwned by %s:%s - %s (%04o)" },
    { "%s (%u MiB)",
      "%s (%u MiB)" },
    { "%s (%u,%u GiB)",
      "%s (%u.%u GiB)" },
    { "%s (Gateway %s)",
      "%s (gateway %s)" },
    { "%s - %u Byte",
      "%s - %u bytes" },
    { "%s - Absatz %d von %d",
      "%s - paragraph %d of %d" },
    { "%s angelegt, Nummer %u, Heim %s",
      "%s created, number %u, home %s" },
    { "%s beendet.",
      "%s ended." },
    { "%s entfernt.",
      "%s removed." },
    { "%s freier Platz - alles Vorhandene bleibt",
      "%s free space - everything present stays" },
    { "%s gehoert %s - das darf nur ein Verwalter beenden.",
      "%s belongs to %s - only an administrator may end it." },
    { "%s gehoert %s:%s",
      "%s is owned by %s:%s" },
    { "%s gehoert jetzt %s:%s",
      "%s is now owned by %s:%s" },
    { "%s hat die Adresse %s",
      "%s has the address %s" },
    { "%s hat jetzt die Rolle %s und darf %s.",
      "%s now has the role %s and may %s." },
    { "%s ist %s Verwalter.",
      "%s is %s administrator." },
    { "%s ist ein eingebauter Befehl: %s",
      "%s is a built-in command: %s" },
    { "%s ist jetzt %s",
      "%s is now %s" },
    { "%s ist kein Bild.",
      "%s is not an image." },
    { "%s kopiert nach %s",
      "%s copied to %s" },
    { "%s laeuft schon nicht mehr.",
      "%s is not running any more." },
    { "%s liess sich nicht schreiben",
      "%s could not be written" },
    { "%s liess sich nicht schreiben.",
      "%s could not be written." },
    { "%s von %s belegt",
      "%s of %s in use" },
    { "%s wirklich entfernen?",
      "Really remove %s?" },
    { "%s, %u Wechsel",
      "%s, %u switches" },
    { "%s: \"%s\" ist ein Ordner",
      "%s: \"%s\" is a folder" },
    { "%s: \"%s\" laesst sich nicht lesen",
      "%s: \"%s\" cannot be read" },
    { "%s: \"%s\" nicht gefunden",
      "%s: \"%s\" not found" },
    { "%u %s in Betrieb, %u Threads, %u %s in Ring 3",
      "%u %s in use, %u threads, %u %s in ring 3" },
    { "%u Aufgaben in %s gesichert",
      "%u tasks saved to %s" },
    { "%u Eintr.",
      "%u items" },
    { "%u Eintraege",
      "%u entries" },
    { "%u Eintraege ausgepackt.",
      "%u entries unpacked." },
    { "%u Eintraege endgueltig geloescht.",
      "%u entries deleted for good." },
    { "%u Eintraege im Dateibaum, %s belegt",
      "%u entries in the file tree, %s in use" },
    { "%u Eintraege in der Pruefspur, davon %u abgewiesen",
      "%u entries in the audit trail, %u of them denied" },
    { "%u Eintraege, %s",
      "%u entries, %s" },
    { "%u Eintraege, %s - \"papierkorb leeren\" raeumt auf",
      "%u entries, %s - \"papierkorb leeren\" clears them out" },
    { "%u KiB von %u KiB benutzt",
      "%u KiB of %u KiB used" },
    { "%u Meldungen im Protokoll, davon %u Warnungen und %u Fehler",
      "%u messages in the log, %u warnings and %u errors among them" },
    { "%u MiB von %u MiB belegt",
      "%u MiB of %u MiB in use" },
    { "%u Ordner, %u Dateien",
      "%u folders, %u files" },
    { "%u Stuecke",
      "%u pieces" },
    { "%u Woerter, %u Zeichen",
      "%u words, %u characters" },
    { "%u Zeichen%s",
      "%u characters%s" },
    { "%u Zeilen, %u Woerter, %u Zeichen  %s",
      "%u lines, %u words, %u characters  %s" },
    { "%u Zellen belegt",
      "%u cells in use" },
    { "%u aeltere sind aus dem Ring gefallen.",
      "%u older ones fell out of the ring." },
    { "%u aktiv",
      "%u active" },
    { "%u ausgepackt, %u uebergangen.",
      "%u unpacked, %u skipped." },
    { "%u empfangen, %u gesendet",
      "%u received, %u sent" },
    { "%u erledigte Aufgaben weggeraeumt.",
      "%u finished tasks cleared away." },
    { "%u in Betrieb",
      "%u in use" },
    { "%u in Ring 3 (%s)",
      "%u in ring 3 (%s)" },
    { "%u ms gewartet.",
      "waited %u ms." },
    { "%u offen von %u",
      "%u open of %u" },
    { "%u offene Aufgaben",
      "%u open tasks" },
    { "%u von %u Eintraegen, davon %u abgewiesen%s",
      "%u of %u entries, %u of them denied%s" },
    { "%u von %u Meldungen - %u Warnungen, %u Fehler",
      "%u of %u messages - %u warnings, %u errors" },
    { "%u x %u, %u Bit",
      "%u x %u, %u bit" },
    { "(automatisch)",
      "(automatic)" },
    { "(fest)",
      "(fixed)" },
    { "(leere Datei)",
      "(empty file)" },
    { "(ohne Namen)",
      "(no name)" },
    { ", eigener Zeitgeber",
      ", own timer" },
    { ", gesperrt",
      ", blocked" },
    { ", ohne Passwort",
      ", no password" },
    { "... (gekuerzt)",
      "... (shortened)" },
    { "8259A-PIC mit PIT",
      "8259A PIC with PIT" },
    { "APIC, %u Kern%s%s",
      "APIC, %u core%s%s" },
    { "Abbrechen",
      "Cancel" },
    { "Abgemeldet",
      "Signed out" },
    { "Abmelden",
      "Sign out" },
    { "Achtung: die Antwort ist unvollstaendig.",
      "Careful: the answer is incomplete." },
    { "Adresse, Gateway, Namensserver, Zaehler",
      "address, gateway, name server, counters" },
    { "Alle",
      "All" },
    { "Alle Regeln entfernt.",
      "All rules removed." },
    { "Alle zeigen",
      "Show all" },
    { "Alles Uebrige steht unter der MIT-Lizenz.",
      "Everything else is under the MIT licence." },
    { "Alles Vorhandene bleibt stehen.",
      "Everything present stays as it is." },
    { "Alles, was darauf steht, geht verloren.",
      "Everything on it will be lost." },
    { "Als Hintergrund",
      "Set as wallpaper" },
    { "Als Hintergrund gesetzt.",
      "Set as wallpaper." },
    { "Angelegt. Zum Behalten speichern.",
      "Created. Save to keep it." },
    { "Anmelden",
      "Sign in" },
    { "Anmeldename:",
      "Login name:" },
    { "Anmeldung freigeben",
      "Allow sign-in" },
    { "Anmeldung sperren",
      "Block sign-in" },
    { "Anteil",
      "Share" },
    { "Arbeitsspeicher",
      "Main memory" },
    { "Archiv",
      "Archive" },
    { "Art, Groesse, Eigentuemer, Rechte, Zeitpunkt und wo er liegt.",
      "Kind, size, owner, permissions, time and where it sits." },
    { "Auf welchen Datentraeger soll das System?",
      "Which disk should the system go on?" },
    { "Aufgaben",
      "Tasks" },
    { "Aufgaben:",
      "Tasks:" },
    { "Aufgabenliste fuehren",
      "keep a task list" },
    { "Aufloesung",
      "Resolution" },
    { "Aufloesung und Vergroesserung",
      "resolution and scaling" },
    { "Aufloesung: %dx%d",
      "Resolution: %dx%d" },
    { "Aufloesungen:",
      "Resolutions:" },
    { "Aufzaehlung",
      "Bullet list" },
    { "Ausfuehren",
      "Run" },
    { "Ausgabe erscheint hier. F5 fuehrt aus.",
      "Output appears here. F5 runs the program." },
    { "Ausgepackt wird in einen Ordner daneben, der wie das Archiv\nheisst. Eintraege mit Pfaden nach draussen werden uebergangen.",
      "Unpacked into a folder next to it, named after the archive.\nEntries with paths leading outside are skipped." },
    { "Auspacken",
      "Unpack" },
    { "Batterieuhr",
      "Hardware clock" },
    { "Bekannte Rollen: %s",
      "Known roles: %s" },
    { "Benutzer",
      "Users" },
    { "Benutzer entfernen",
      "Remove user" },
    { "Benutzer wechseln",
      "Switch user" },
    { "Benutzer:",
      "Users:" },
    { "Bereiche: Dateien, Text, Programme, System, Netz, Sicherheit",
      "Groups: Files, Text, Programs, System, Network, Security" },
    { "Betriebsart",
      "Mode" },
    { "Bewegt sich der Zeiger nicht, steht hier, ob ueberhaupt Bytes\nankommen und ueber welchen Weg.",
      "If the pointer does not move, this says whether any bytes arrive\nat all, and by which route." },
    { "Bild",
      "Image" },
    { "Bild waehlen",
      "Choose image" },
    { "Bilder",
      "Images" },
    { "Bildschirm",
      "Screen" },
    { "Bildschirm loeschen",
      "clear the screen" },
    { "Bildschirm sperren",
      "lock the screen" },
    { "Bildschirm: %dx%d, %ux vergroessert",
      "Display: %dx%d, scaled %ux" },
    { "Bildschirmfoto",
      "Screenshot" },
    { "Bildschirmfoto aufnehmen",
      "take a screenshot" },
    { "Bitte nicht ausschalten.",
      "Please do not switch off." },
    { "Browser",
      "Browser" },
    { "Browser - %s",
      "Browser - %s" },
    { "Da laeuft nichts mehr.",
      "Nothing is running there any more." },
    { "Da steht noch nichts.",
      "There is nothing there yet." },
    { "Dafuer braucht es Verwalterrechte.",
      "That needs administrator rights." },
    { "Dafuer braucht es das Recht am Netz.",
      "That needs the network permission." },
    { "Dafuer braucht es das Recht an den Konten.",
      "That needs the accounts permission." },
    { "Danach ist der Datentraeger leer.",
      "Afterwards the disk is empty." },
    { "Daneben      : installieren <name> daneben",
      "Alongside    : installieren <name> daneben" },
    { "Daneben einrichten",
      "Install alongside" },
    { "Das Archiv entsteht daneben und heisst wie das Gepackte, mit\n.zip dahinter. Ordner kommen mit allem Inhalt hinein.",
      "The archive appears next to it, named after what was packed with\n.zip appended. Folders go in with everything inside." },
    { "Das Archiv ist nicht mehr da.",
      "The archive is gone." },
    { "Das Archiv liess sich nicht abschliessen.",
      "The archive could not be closed." },
    { "Das Archiv liess sich nicht fuellen.",
      "The archive could not be filled." },
    { "Das Bild landet als PNG im eigenen Bilder-Ordner.",
      "The picture lands as a PNG in your own image folder." },
    { "Das Bild liess sich nicht laden.",
      "The image could not be loaded." },
    { "Das Bild wird im naechsten Bildaufbau gemacht.",
      "The picture is taken with the next frame." },
    { "Das darf nur der Eigentuemer oder ein Verwalter.",
      "Only the owner or an administrator may do that." },
    { "Das geht bei diesem Benutzer nicht.",
      "That is not possible for this user." },
    { "Das ist kein Archiv.",
      "That is not an archive." },
    { "Das laesst sich nicht packen.",
      "That cannot be packed." },
    { "Das loescht alle Daten auf dem Datentraeger.",
      "This erases all data on the disk." },
    { "Das loescht alles auf %s (%s).",
      "This erases everything on %s (%s)." },
    { "Datei als Zahlen und Zeichen",
      "a file as numbers and characters" },
    { "Datei ausgeben",
      "print a file" },
    { "Datei im Editor oeffnen",
      "open a file in the editor" },
    { "Datei nicht gefunden: %s",
      "File not found: %s" },
    { "Datei oder Ordner kopieren",
      "copy a file or folder" },
    { "Datei:",
      "File:" },
    { "Dateien",
      "Files" },
    { "Dateien nach Namensmuster suchen",
      "find files by name pattern" },
    { "Dateien und Protokoll",
      "Files and log" },
    { "Dateien unter /Festplatte bleiben ab jetzt liegen.",
      "Files under /Festplatte are kept from now on." },
    { "Dateimanager",
      "Files" },
    { "Dateimanager - %s",
      "Files - %s" },
    { "Dateiname:",
      "File name:" },
    { "Dateisystem",
      "File system" },
    { "Datentraeger",
      "Storage" },
    { "Datentraeger neu mit FAT32 formatieren",
      "format a disk afresh with FAT32" },
    { "Datum und Uhrzeit",
      "date and time" },
    { "Dauerhaft speichern darf nur, wer das Recht an den Einstellungen hat.",
      "Only someone with the settings permission may save this permanently." },
    { "Dauerhaft wird das erst mit Speichern in den Einstellungen.",
      "It only becomes permanent by saving in the settings." },
    { "Der Arbeitsthread liess sich nicht starten.",
      "The worker thread could not be started." },
    { "Der Benutzer liess sich nicht anlegen.",
      "The user could not be created." },
    { "Der Datentraeger ist jetzt in einem halben Zustand.",
      "The disk is now in a half-finished state." },
    { "Der Deuter liess sich nicht anlegen - zu wenig Speicher.\n",
      "The interpreter could not be created - not enough memory.\n" },
    { "Der Download ist fehlgeschlagen.",
      "The download failed." },
    { "Der Modus ist \"750\" oder \"rwxr-x---\".",
      "The mode is \"750\" or \"rwxr-x---\"." },
    { "Der Name konnte nicht geaendert werden.",
      "The name could not be changed." },
    { "Der Ordner konnte nicht angelegt werden. Moeglicherweise gibt es ihn bereits.",
      "The folder could not be created. It may already exist." },
    { "Der Papierkorb ist leer.",
      "The trash is empty." },
    { "Der Rechner startet danach von dieser Platte - ueber UEFI",
      "The machine will then boot from this disk - over UEFI" },
    { "Der Rechner startet jetzt RetroOS.",
      "The machine now boots RetroOS." },
    { "Der Zielordner liess sich nicht anlegen.",
      "The target folder could not be created." },
    { "Der alte Platz ist nicht mehr erreichbar.",
      "The original place is no longer reachable." },
    { "Der uebliche Startpfad war belegt - RetroOS steht unter EFI\\RETROOS und muss im Startmenue der Firmware gewaehlt werden.",
      "The usual boot path was taken - RetroOS sits at EFI\\RETROOS and has to be picked from the firmware boot menu." },
    { "Der uebliche Startpfad war belegt: RetroOS steht unter",
      "The usual boot path was taken: RetroOS sits at" },
    { "Deutsch (QWERTZ)",
      "German (QWERTZ)" },
    { "Di",
      "Tu" },
    { "Die Anmeldung ist gesperrt.",
      "Signing in is blocked." },
    { "Die Anmeldung ist wieder frei.",
      "Signing in is allowed again." },
    { "Die Anteile werden jede Sekunde neu gemessen.",
      "The shares are measured afresh every second." },
    { "Die Datei konnte nicht angelegt werden. Moeglicherweise gibt es sie bereits.",
      "The file could not be created. It may already exist." },
    { "Die Datei konnte nicht geschrieben werden.",
      "The file could not be written." },
    { "Die Datei laesst sich nicht lesen.",
      "The file cannot be read." },
    { "Die Datei liess sich nicht anlegen.",
      "The file could not be created." },
    { "Die Datei liess sich nicht schreiben.",
      "The file could not be written." },
    { "Die Datei wurde inzwischen geloescht. Der Text ist noch da, hat aber kein Ziel mehr.",
      "The file has been deleted in the meantime. The text is still here but has nowhere to go." },
    { "Die Dateien sind gleich.",
      "The files are the same." },
    { "Die Installation ist abgeschlossen.",
      "The installation is complete." },
    { "Die Installation ist gescheitert:",
      "The installation failed:" },
    { "Die Liste ist voll.",
      "The list is full." },
    { "Die Platte wurde nicht fertig.",
      "The disk was not finished." },
    { "Die Pruefspur lesen darf nur, wer das Recht am Protokoll hat.",
      "Only someone with the log permission may read the audit trail." },
    { "Die Seite konnte nicht geladen werden.",
      "The page could not be loaded." },
    { "Die Sprache gilt sofort - die Tastatur ist mitgewandert.",
      "The language applies at once - the keyboard moved along with it." },
    { "Die Uhr kommt aus der Batterieuhr des Rechners.",
      "The time comes from the machine's hardware clock." },
    { "Die Zeit ist um.",
      "Time is up." },
    { "Diese Datei gehoert zum System und ist schreibgeschuetzt.",
      "This file belongs to the system and is read-only." },
    { "Diese Datei gibt es nicht.",
      "There is no such file." },
    { "Diese Grafikkarte laesst den Modus nicht wechseln.",
      "This graphics adapter does not allow a mode change." },
    { "Diese Regel gibt es nicht.",
      "There is no such rule." },
    { "Diese Vergroesserung geht hier nicht.",
      "That scaling does not work here." },
    { "Dieser Eintrag gehoert zum System und laesst sich nicht loeschen.",
      "This entry belongs to the system and cannot be deleted." },
    { "Dieser Ordner ist leer.",
      "This folder is empty." },
    { "Do",
      "Th" },
    { "Downloads",
      "Downloads" },
    { "Drei Fehlversuche - %u Sekunden Pause",
      "Three failed attempts - %u second pause" },
    { "Durchgelaufen - aber ohne Ausgabe. console.log() sagt etwas.\n",
      "Ran through - but without output. console.log() says something.\n" },
    { "EFI\\RETROOS und muss im Startmenue gewaehlt werden.",
      "EFI\\RETROOS and has to be picked from the boot menu." },
    { "Editor",
      "Editor" },
    { "Editor - %s%s",
      "Editor - %s%s" },
    { "Eigenschaften",
      "Properties" },
    { "Eigentuemer zeigen oder setzen",
      "show or set the owner" },
    { "Ein kleines Betriebssystem fuer x86-64-Rechner,",
      "A small operating system for x86-64 machines," },
    { "Ein zweiter Versuch legt ihn neu an.",
      "A second attempt lays it out afresh." },
    { "Eine offene Aufgabe",
      "One open task" },
    { "Eingabe",
      "Input" },
    { "Eingehaengt: /Festplatte (%s)",
      "Mounted: /Festplatte (%s)" },
    { "Einstellungen",
      "Settings" },
    { "Endgueltig",
      "Delete for good" },
    { "Englisch (QWERTY)",
      "English US (QWERTY)" },
    { "Englisch GB (QWERTY)",
      "English UK (QWERTY)" },
    { "Entfernt. Das Heimatverzeichnis bleibt stehen.",
      "Removed. The home directory stays." },
    { "Erledigte weg",
      "Clear done" },
    { "Erreichbarkeit pruefen",
      "check whether something answers" },
    { "Erwartet wird \"750\" oder \"rwxr-x---\".",
      "Expected \"750\" or \"rwxr-x---\"." },
    { "Erwartet wird 15.09.2026 oder ein Strich.",
      "Expected 15.09.2026 or a dash." },
    { "Erwartet wird hoch, mittel oder niedrig.",
      "Expected high, medium or low." },
    { "Es fehlt der Name.",
      "The name is missing." },
    { "Es gibt + - * / % und Klammern, Punkt vor Strich.",
      "There are + - * / % and parentheses, times before plus." },
    { "Es gibt kein Bild zum Speichern.",
      "There is nothing to save." },
    { "Es gibt keinen Ordner fuer Bilder.",
      "There is no folder for images." },
    { "Es gibt keinen Papierkorb.",
      "There is no trash." },
    { "Es gibt noch keine Benutzerdatenbank - melde dich als root an.",
      "There is no user database yet - sign in as root." },
    { "Es gibt ungespeicherte Aenderungen.",
      "There are unsaved changes." },
    { "Es ist kein Platz fuer weitere Regeln.",
      "There is no room for more rules." },
    { "Es ist nichts erledigt.",
      "Nothing is finished." },
    { "Es kommt nichts an.",
      "Nothing is arriving." },
    { "Es laeuft kein Programm mit der Nummer %u",
      "No program is running with number %u" },
    { "Es laeuft schon ein Auftrag.",
      "A job is already running." },
    { "Es steht noch nichts da.\n",
      "There is nothing here yet.\n" },
    { "Es wurde kein Datentraeger gefunden.",
      "No disk was found." },
    { "F5 fuehrt aus",
      "F5 runs it" },
    { "FAT32 \"%s\" unter /Festplatte",
      "FAT32 \"%s\" at /Festplatte" },
    { "Fehler",
      "Errors" },
    { "Fehler: ",
      "Error: " },
    { "Fehlgeschlagen",
      "Failed" },
    { "Fertig",
      "Done" },
    { "Fertig.",
      "Done." },
    { "Fertig. /Festplatte ist wieder da.",
      "Done. /Festplatte is back." },
    { "Fertig. Das Startmedium kann jetzt entfernt werden.",
      "Done. The boot medium can be removed now." },
    { "Fett",
      "Bold" },
    { "Folie",
      "Slide" },
    { "Folie %d von %d - %s",
      "Slide %d of %d - %s" },
    { "Formatiere ...",
      "Formatting ..." },
    { "Formatieren fehlgeschlagen.",
      "Formatting failed." },
    { "Fr",
      "Fr" },
    { "Fremde Programme beendet nur ein Verwalter.",
      "Only an administrator ends someone else's program." },
    { "Ganze Platte : installieren <name> wirklich",
      "Whole disk   : installieren <name> wirklich" },
    { "Geloescht: %s",
      "Deleted: %s" },
    { "Geloeschtes ansehen und zurueckholen",
      "see and restore deleted things" },
    { "Gemessen wird nach dem Systemtakt.",
      "Measured against the system timer." },
    { "Geraet",
      "Device" },
    { "Geraete am USB-Bus",
      "devices on the USB bus" },
    { "Gesichert in %s",
      "Saved to %s" },
    { "Gespeichert - aber %s ist Verwalter ohne Passwort.",
      "Saved - but %s is an administrator without a password." },
    { "Gespeichert als %s",
      "Saved as %s" },
    { "Gespeichert in %s",
      "Saved to %s" },
    { "Gespeichert. Ab dem naechsten Start wird angemeldet.",
      "Saved. From the next start on, signing in is required." },
    { "Gespeichert: %s (%s)%s",
      "Saved: %s (%s)%s" },
    { "Gesperrt",
      "Locked" },
    { "Grafik und Dateien",
      "Graphics and files" },
    { "Grau",
      "Grey" },
    { "Gross- und Kleinschreibung sind gleich. Ist der Pfad ein Ordner,\nwird alles darunter durchsucht.",
      "Upper and lower case are the same. If the path is a folder,\neverything below it is searched." },
    { "Grundeinstellung %s: %s",
      "Default %s: %s" },
    { "Gruppen und ihre Mitglieder",
      "groups and their members" },
    { "Gruppen:",
      "Groups:" },
    { "Haken setzen",
      "Tick off" },
    { "Halt",
      "Stop" },
    { "Hardware-Adresse",
      "Hardware address" },
    { "Hersteller",
      "Vendor" },
    { "Herunterfahren",
      "Shut down" },
    { "Herunterladen geht nur aus dem Netz.",
      "Downloading only works from the network." },
    { "Heute",
      "Today" },
    { "Hintergrund",
      "Background" },
    { "Hintergrundbild",
      "Wallpaper" },
    { "Hinweise",
      "Notices" },
    { "Hinzufuegen",
      "Add" },
    { "IP-Adresse",
      "IP address" },
    { "Im Muster steht * fuer beliebig viele Zeichen und ? fuer eines.",
      "In the pattern * stands for any number of characters and ? for one." },
    { "In VirtualBox: System - Mainboard - Zeigegeraet auf \"PS/2-Maus\" stellen.",
      "In VirtualBox: System - Motherboard - Pointing Device to \"PS/2 Mouse\"." },
    { "Innerhalb eines Dateisystems wird nur umgehaengt - es wird kein\nByte angefasst. Ueber die Grenze hinweg wird kopiert und geloescht.",
      "Within one file system only the link moves - not a byte is touched.\nAcross the boundary it is copied and then deleted." },
    { "Installation laeuft",
      "Installing" },
    { "Installiere auf %s ...",
      "Installing on %s ..." },
    { "Installiere neben dem Vorhandenen auf %s ...",
      "Installing alongside what is on %s ..." },
    { "Installieren",
      "Install" },
    { "Ist das Ziel ein Ordner, landet die Kopie darin unter demselben\nNamen. Ordner werden mit allem Inhalt kopiert.",
      "If the target is a folder, the copy lands inside it under the same\nname. Folders are copied with everything in them." },
    { "Ist der uebliche Startpfad belegt, muss RetroOS im",
      "If the usual boot path is taken, RetroOS has to be picked" },
    { "Ist jetzt Verwalter.",
      "Is an administrator now." },
    { "Ist kein Verwalter mehr.",
      "Is no longer an administrator." },
    { "Ja",
      "Yes" },
    { "Kaefig",
      "Cage" },
    { "Kaefigprofile:",
      "Cage profiles:" },
    { "Kalender",
      "Calendar" },
    { "Karte",
      "Adapter" },
    { "Kein Benutzer ausgewaehlt.",
      "No user selected." },
    { "Kein Datentraeger gefunden.",
      "No disk found." },
    { "Kein FAT32-Dateisystem eingehaengt.",
      "No FAT32 file system mounted." },
    { "Kein Speicher.",
      "Out of memory." },
    { "Kein freier Arbeits-Thread.",
      "No free worker thread." },
    { "Kein geeigneter Datentraeger dabei.",
      "No suitable disk among them." },
    { "Keine Aufgabenliste gefunden.",
      "No task list found." },
    { "Keine Netzwerkkarte gefunden.",
      "No network adapter found." },
    { "Keine Netzwerkverbindung.",
      "No network connection." },
    { "Keine Seite geladen.",
      "No page loaded." },
    { "Keine USB-Geraete gefunden.",
      "No USB devices found." },
    { "Keine Wurzel",
      "No square root" },
    { "Kern",
      "Core" },
    { "Kern %u: %s, %u Takte, %u Wechsel",
      "Core %u: %s, %u ticks, %u switches" },
    { "Kerne",
      "Cores" },
    { "Kernel-Heap",
      "Kernel heap" },
    { "Kernel-Heap: %s von %s",
      "Kernel heap: %s of %s" },
    { "Konsole",
      "Console" },
    { "Konten legst du unter \"Benutzer\" an - ab dann",
      "You create accounts under \"Users\" - from then on" },
    { "Konten zeigen und verwalten",
      "show and manage accounts" },
    { "Kurzzeit",
      "Timer" },
    { "Lade ...",
      "Loading ..." },
    { "Lade Bestandteil %u von %u ...",
      "Loading part %u of %u ..." },
    { "Lade Bestandteile ...",
      "Loading parts ..." },
    { "Lade herunter: %s",
      "Downloading: %s" },
    { "Laufwerk",
      "Drive" },
    { "Laufwerke und eingehaengtes Dateisystem",
      "drives and mounted file system" },
    { "Laufzeit",
      "Uptime" },
    { "Laufzeit %u:%02u:%02u",
      "Uptime %u:%02u:%02u" },
    { "Laufzeit: %u:%02u:%02u",
      "Uptime: %u:%02u:%02u" },
    { "Leeren",
      "Clear" },
    { "Leeren darf nur, wer das Recht am Protokoll hat.",
      "Only someone with the log permission may clear it." },
    { "Liste",
      "List" },
    { "Loeschen",
      "Delete" },
    { "Long Mode (64 Bit)",
      "Long mode (64 bit)" },
    { "Los",
      "Go" },
    { "Maschine",
      "Machine" },
    { "Maus",
      "Mouse" },
    { "Mehrfach genutzt: %u KiB",
      "Shared: %u KiB" },
    { "Mi",
      "We" },
    { "Mit -l stehen Rechte, Eigentuemer und Gruppe davor.",
      "With -l, permissions, owner and group stand in front." },
    { "Mit den Pfeiltasten nach oben und unten holt man sie zurueck.",
      "The up and down arrow keys bring them back." },
    { "Mit einem Bereich nur dessen Befehle: Dateien, Text, Programme,\nSystem, Netz, Sicherheit.",
      "With a group, only its commands: Files, Text, Programs,\nSystem, Network, Security." },
    { "Mo",
      "Mo" },
    { "Modell",
      "Model" },
    { "Moegliche Ziele:",
      "Possible targets:" },
    { "Nachrichten kann RetroOS nicht verschicken: %s",
      "RetroOS cannot send mail: %s" },
    { "Nachtblau",
      "Midnight blue" },
    { "Name",
      "Name" },
    { "Name der neuen Datei:",
      "Name of the new file:" },
    { "Name des neuen Ordners:",
      "Name of the new folder:" },
    { "Name oder Passwort stimmt nicht.",
      "Name or password is wrong." },
    { "Namen in eine Adresse wandeln",
      "turn a name into an address" },
    { "Nein",
      "No" },
    { "Netz",
      "Network" },
    { "Netzwerk",
      "Network" },
    { "Neu starten",
      "Restart" },
    { "Neue Aufgabe eintippen und Eingabe druecken",
      "Type a new task and press Enter" },
    { "Neue Datei",
      "New file" },
    { "Neuer Benutzer",
      "New user" },
    { "Neuer Name:",
      "New name:" },
    { "Neuer Ordner",
      "New folder" },
    { "Neues Passwort fuer %s:",
      "New password for %s:" },
    { "Nicht durch null",
      "Cannot divide by zero" },
    { "Nichts an diesem Tag.",
      "Nothing on this day." },
    { "Nichts passt auf \"%s\".",
      "Nothing matches \"%s\"." },
    { "Nichts wird geloescht - RetroOS nimmt nur den freien Platz.",
      "Nothing is erased - RetroOS only takes the free space." },
    { "Nichts zu tun.",
      "Nothing to do." },
    { "Niemand angemeldet - alles laeuft als root.",
      "Nobody signed in - everything runs as root." },
    { "Noch %u Sekunden warten.",
      "Wait another %u seconds." },
    { "Noch keine Datenbank - RetroOS meldet sich ohne Nachfrage als root an.",
      "No database yet - RetroOS signs in as root without asking." },
    { "Noch nichts eingegeben.",
      "Nothing entered yet." },
    { "Noetig ist das RetroOS-Abbild (ISO oder USB-Stick).",
      "The RetroOS image is needed (ISO or USB stick)." },
    { "Notiert: %s",
      "Noted: %s" },
    { "Nullstellen",
      "Reset" },
    { "Nummer",
      "Number" },
    { "Nummer %u, Gruppe %s%s%s",
      "Number %u, group %s%s%s" },
    { "Nur offene",
      "Open only" },
    { "Oder daneben, ohne etwas zu loeschen: installieren <name> daneben",
      "Or alongside, erasing nothing: installieren <name> daneben" },
    { "Oeffnen",
      "Open" },
    { "Offene Fenster",
      "Open windows" },
    { "Ohne Angabe der laufende Monat, der heutige Tag in Klammern.",
      "Without arguments the current month, today in brackets." },
    { "Ohne Angabe die ersten 256 Bytes.",
      "Without a count, the first 256 bytes." },
    { "Ohne Angabe sind es zehn.",
      "Without a count it is ten." },
    { "Ohne Angabe stehen die Profile mit ihren Rechten da.",
      "Without arguments the profiles and their rights are listed." },
    { "Ohne Angabe stehen die moeglichen Aufloesungen da. Die\nVergroesserung blaest jeden Punkt zum Quadrat auf - auf einem\nsehr feinen Bildschirm ist die Schrift damit wieder lesbar.",
      "Without arguments the possible resolutions are listed. Scaling\nblows every point up into a square - on a very fine display that\nmakes the text readable again." },
    { "Ohne Angabe stehen die verfuegbaren Sprachen da. Die Tastatur\nwandert mit, solange sie nicht von Hand gesetzt wurde.",
      "Without arguments the available languages are listed. The keyboard\nmoves along, as long as it was not set by hand." },
    { "Ohne Festplatte bleibt nichts gespeichert.",
      "Without a hard disk nothing is kept." },
    { "Ohne Festplatte gilt das bis zum Ausschalten.",
      "Without a hard disk this lasts until shutdown." },
    { "Ohne Festplatte gilt das nur bis zum Ausschalten.",
      "Without a hard disk this only lasts until shutdown." },
    { "Ohne Tiefe geht es drei Ebenen hinunter.",
      "Without a depth it goes down three levels." },
    { "Ohne Verwalterrechte laesst sich nur das eigene Passwort aendern.",
      "Without administrator rights only your own password can be changed." },
    { "Ordner",
      "Folder" },
    { "Ordner \"%s\" in den Papierkorb legen?",
      "Move folder \"%s\" to the trash?" },
    { "Ordner als Baum zeichnen",
      "draw a folder as a tree" },
    { "Ordner anlegen",
      "create a folder" },
    { "Ordner wechseln",
      "change folder" },
    { "Ordnerinhalt anzeigen",
      "list a folder" },
    { "Ortszeit",
      "Local time" },
    { "PS/2-Anschluss",
      "PS/2 port" },
    { "Packen",
      "Pack" },
    { "Pakete",
      "Packets" },
    { "Paketfilter %s.",
      "Packet filter %s." },
    { "Paketfilter zeigen und regeln",
      "show and set the packet filter" },
    { "Paketfilter: %s",
      "Packet filter: %s" },
    { "Papierkorb",
      "Trash" },
    { "Passwort",
      "Password" },
    { "Passwort aendern",
      "Change password" },
    { "Passwort fuer den neuen Benutzer (leer heisst: keines):",
      "Password for the new user (empty means none):" },
    { "Passwort geloescht - die Anmeldung geht jetzt ohne.",
      "Password removed - signing in now works without one." },
    { "Passwort gesetzt. Zum Behalten speichern.",
      "Password set. Save to keep it." },
    { "Passwort von %s gesetzt.",
      "Password of %s set." },
    { "Pfad des Bildes (PNG, JPEG, GIF oder BMP):",
      "Path of the image (PNG, JPEG, GIF or BMP):" },
    { "Physischer Speicher",
      "Physical memory" },
    { "Ping an %s (%s):",
      "Ping to %s (%s):" },
    { "Platzbedarf eines Ordners",
      "space used by a folder" },
    { "Programm",
      "Program" },
    { "Programm beenden",
      "End program" },
    { "Programme",
      "Programs" },
    { "Programmieren",
      "Code" },
    { "Programmieren - %s%s",
      "Code - %s%s" },
    { "Protokoll",
      "Log" },
    { "Protokoll geleert.",
      "Log cleared." },
    { "Prozessor",
      "Processor" },
    { "Pruefsumme einer Datei",
      "checksum of a file" },
    { "Rechenzeit",
      "CPU time" },
    { "Rechner",
      "Calculator" },
    { "Rechner bootet dann von der Festplatte.",
      "will then boot from the hard disk." },
    { "Rechner neu starten",
      "restart the machine" },
    { "Rechnername",
      "Computer name" },
    { "Rechte",
      "Permissions" },
    { "Rechte zeigen oder setzen",
      "show or set permissions" },
    { "Regel %d angelegt.",
      "Rule %d created." },
    { "Regel %u entfernt.",
      "Rule %u removed." },
    { "Regeln werden von oben nach unten geprueft, die erste passende\nentscheidet. Passt keine, gilt die Grundeinstellung.",
      "Rules are checked from top to bottom, the first match decides.\nIf none matches, the default applies." },
    { "RetroOS 1.0 (x86-64)",
      "RetroOS 1.0 (x86-64)" },
    { "RetroOS auf %s",
      "RetroOS on %s" },
    { "RetroOS auf eine Festplatte bringen",
      "Put RetroOS on a hard disk" },
    { "RetroOS auf eine Platte bringen",
      "put RetroOS on a disk" },
    { "RetroOS installieren",
      "Install RetroOS" },
    { "RetroOS legt zwei Abschnitte an:",
      "RetroOS creates two partitions:" },
    { "RetroOS liegt jetzt auf der Platte.",
      "RetroOS is on the disk now." },
    { "RetroOS-Konsole 1.0",
      "RetroOS console 1.0" },
    { "Rolle %s - darf %s",
      "Role %s - may %s" },
    { "Rufe %s ab ...",
      "Fetching %s ..." },
    { "SHA-256, dieselbe, die auch anderswo gerechnet wird.",
      "SHA-256, the same one everybody else computes." },
    { "Sa",
      "Sa" },
    { "Schreiben",
      "Writer" },
    { "Schreiben - %s%s",
      "Writer - %s%s" },
    { "Schrift",
      "Font" },
    { "Schrift: %s",
      "Font: %s" },
    { "Schriftarten zeigen oder waehlen",
      "show or choose fonts" },
    { "Schriftarten:",
      "Fonts:" },
    { "Schweiz (QWERTZ)",
      "Swiss (QWERTZ)" },
    { "Seite abrufen und wahlweise speichern",
      "fetch a page and optionally save it" },
    { "Seitentext kopiert (%u Zeichen)",
      "Page text copied (%u characters)" },
    { "Sicherheit",
      "Security" },
    { "Sicherheitsereignisse ansehen",
      "look at security events" },
    { "So",
      "Su" },
    { "Speicher",
      "Memory" },
    { "Speicherbelegung",
      "memory in use" },
    { "Speichern",
      "Save" },
    { "Speichern unter",
      "Save as" },
    { "Sperren",
      "Lock" },
    { "Sprache",
      "Language" },
    { "Sprache zeigen oder umschalten",
      "show or switch the language" },
    { "Sprachen:",
      "Languages:" },
    { "Start",
      "Start" },
    { "Startmedium entfernen und neu starten - der",
      "Remove the boot medium and restart - the machine" },
    { "Startmenue der Firmware gewaehlt werden.",
      "from the firmware boot menu." },
    { "Startseite",
      "Start page" },
    { "Stoppuhr",
      "Stopwatch" },
    { "Summe",
      "Sum" },
    { "System",
      "System" },
    { "Systeminformation",
      "System information" },
    { "Systemmonitor",
      "System monitor" },
    { "Systemprotokoll zeigen und sichern",
      "show and save the system log" },
    { "Systemversion",
      "system version" },
    { "TT.MM.JJJJ oder ein Strich",
      "DD.MM.YYYY or a dash" },
    { "Tabelle",
      "Sheet" },
    { "Tabelle - %s%s",
      "Sheet - %s%s" },
    { "Tabulator wechselt das Feld, Eingabe meldet an.",
      "Tab moves between fields, Enter signs in." },
    { "Tastatur",
      "Keyboard" },
    { "Tastatur und Maus",
      "Keyboard and mouse" },
    { "Tastaturbelegungen:",
      "Keyboard layouts:" },
    { "Termin",
      "Due date" },
    { "Termin fuer \"%s\" (TT.MM.JJJJ, Strich loescht ihn):",
      "Due date for \"%s\" (DD.MM.YYYY, a dash removes it):" },
    { "Termin von %s: %s",
      "Due date of %s: %s" },
    { "Text",
      "Text" },
    { "Text an eine Datei anhaengen",
      "append text to a file" },
    { "Text ausgeben",
      "print text" },
    { "Text in Dateien suchen",
      "search files for text" },
    { "Textkoerper",
      "Body text" },
    { "Threads",
      "Threads" },
    { "Titel",
      "Title" },
    { "Titelfolie",
      "Title slide" },
    { "Tuerkis",
      "Turquoise" },
    { "USB-Anschluss %u",
      "USB port %u" },
    { "Ueber RetroOS",
      "About RetroOS" },
    { "Ueberschrift 1",
      "Heading 1" },
    { "Ueberschrift 2",
      "Heading 2" },
    { "Uhr",
      "Clock" },
    { "Umbenennen",
      "Rename" },
    { "Unbekannt: %s",
      "Unknown: %s" },
    { "Unbekannte Angabe: %s",
      "Unknown value: %s" },
    { "Unbekannte Gruppe: %s",
      "Unknown group: %s" },
    { "Unbekannte Schrift: %s",
      "Unknown font: %s" },
    { "Unbekannte Sprache: %s",
      "Unknown language: %s" },
    { "Unbekannter Befehl: %s  (\"hilfe\" zeigt alle Befehle)",
      "Unknown command: %s  (\"hilfe\" lists them all)" },
    { "Unbekannter Benutzer: %s",
      "Unknown user: %s" },
    { "Unbenannt",
      "Untitled" },
    { "Unter diesem Namen geht es nicht.",
      "That name will not work." },
    { "Unterbrechungen",
      "Interrupts" },
    { "Vergroesserung",
      "Scaling" },
    { "Vergroesserung: %ux%s",
      "Scaling: %ux%s" },
    { "Vergroesserung: 1x bis %ux, dazu \"auto\".",
      "Scaling: 1x to %ux, plus \"auto\"." },
    { "Verschenken darf nur ein Verwalter.",
      "Only an administrator may give something away." },
    { "Verschluesselt: %s",
      "Encrypted: %s" },
    { "Version 1.0",
      "Version 1.0" },
    { "Verteiler",
      "Hub" },
    { "Verwalterrecht nehmen",
      "Revoke admin" },
    { "Von diesem Startmedium laesst sich nicht installieren.",
      "There is no installing from this boot medium." },
    { "Von diesem Startmedium laesst sich nicht installieren.\nNoetig ist das RetroOS-Abbild als ISO oder auf einem USB-Stick.",
      "There is no installing from this boot medium.\nThe RetroOS image is needed, as an ISO or on a USB stick." },
    { "Von vorn",
      "Start over" },
    { "Vorfuehren",
      "Present" },
    { "Vorrang",
      "Priority" },
    { "Vortrag",
      "Slides" },
    { "Vortrag - %s%s",
      "Slides - %s%s" },
    { "Waldgruen",
      "Forest green" },
    { "Warnungen",
      "Warnings" },
    { "Was schon im Papierkorb liegt, wird endgueltig geloescht.",
      "Whatever is already in the trash is deleted for good." },
    { "Weg",
      "Remove" },
    { "Weinrot",
      "Wine red" },
    { "Weiter",
      "Next" },
    { "Welche Aufgabe? Nummer aus der Liste angeben.",
      "Which task? Give a number from the list." },
    { "Wichtigkeit",
      "Priority" },
    { "Wichtigkeit von \"%s\" (hoch, mittel, niedrig):",
      "Priority of \"%s\" (high, medium, low):" },
    { "Wiederherstellen",
      "Restore" },
    { "Wird vorbereitet ...",
      "Preparing ..." },
    { "Wirklich?",
      "Are you sure?" },
    { "Wurzel",
      "Sqrt" },
    { "Zaehlt alles darunter zusammen und zeigt die groessten zuerst.",
      "Adds up everything below it and shows the largest first." },
    { "Zeigegeraet und woran es haengt",
      "the pointing device and what it hangs on" },
    { "Zeigegeraet:",
      "Pointing device:" },
    { "Zeigt die erste Zeile, in der sie sich unterscheiden.",
      "Shows the first line where they differ." },
    { "Zeile",
      "Line" },
    { "Zeile %d von %d, Spalte %d",
      "Line %d of %d, column %d" },
    { "Zeile %u:",
      "Line %u:" },
    { "Zeilen sortiert ausgeben",
      "print lines in order" },
    { "Zeilen, Woerter und Zeichen zaehlen",
      "count lines, words and characters" },
    { "Zeit",
      "Time" },
    { "Zeit        Art        Ausgang     Benutzer   Gegenstand",
      "Time        Kind       Outcome     User       Subject" },
    { "Zeit seit dem Einschalten",
      "time since switching on" },
    { "Zeitzone",
      "Time zone" },
    { "Ziel: %s - %s (%s)",
      "Target: %s - %s (%s)" },
    { "Zitat",
      "Quote" },
    { "Zu diesem Text gehoert keine Datei.",
      "There is no file behind this text." },
    { "Zu gross",
      "Too large" },
    { "Zu viele Versuche - bitte kurz warten.",
      "Too many attempts - please wait a moment." },
    { "Zu wenig Platz fuer den Download.",
      "Not enough room for the download." },
    { "Zu wenig Speicher fuer das Bild.",
      "Not enough memory for the image." },
    { "Zu wenig Speicher.",
      "Not enough memory." },
    { "Zum Bestaetigen: formatieren wirklich [Bezeichnung]",
      "To confirm: formatieren wirklich [label]" },
    { "Zum Bestaetigen: installieren %s wirklich",
      "To confirm: installieren %s wirklich" },
    { "Zum Verwalter machen",
      "Make administrator" },
    { "Zurueck",
      "Back" },
    { "Zurzeit laeuft kein Programm.",
      "No program is running right now." },
    { "Zustand",
      "State" },
    { "Zwischenzeit",
      "Lap" },
    { "[%s abgebrochen]",
      "[%s stopped]" },
    { "[%s beendet, Ergebnis %d]",
      "[%s ended, result %d]" },
    { "[%s laeuft als Nummer %u im Kaefig \"%s\": %s]",
      "[%s runs as number %u in the \"%s\" cage: %s]" },
    { "[%s laeuft als Nummer %u]",
      "[%s runs as number %u]" },
    { "abgebrochen",
      "stopped" },
    { "aktuellen Pfad anzeigen",
      "show the current path" },
    { "alles loeschen: %s Startbereich, %s Ablage",
      "erase everything: %s boot area, %s storage" },
    { "alles ueber einen Eintrag",
      "everything about an entry" },
    { "alles zu einem einzelnen Befehl",
      "everything about a single command" },
    { "angehalten",
      "paused" },
    { "angemeldet",
      "attached" },
    { "angemeldeter Benutzer, Rolle und Gruppen",
      "the signed-in user, their role and groups" },
    { "auf der Platte",
      "on the disk" },
    { "aufgaben neu <text>",
      "aufgaben neu <text>" },
    { "aufloesen: %s nicht gefunden",
      "aufloesen: %s not found" },
    { "aufloesen: Name fehlt",
      "aufloesen: name missing" },
    { "baum: \"%s\" ist kein Ordner",
      "tree: \"%s\" is not a folder" },
    { "beende <nummer>",
      "kill <number>" },
    { "beendet",
      "ended" },
    { "bereit",
      "ready" },
    { "besitzer: \"%s\" nicht gefunden",
      "besitzer: \"%s\" not found" },
    { "cat: \"%s\" ist ein Ordner",
      "cat: \"%s\" is a folder" },
    { "cat: \"%s\" laesst sich nicht lesen",
      "cat: \"%s\" cannot be read" },
    { "cat: \"%s\" nicht gefunden",
      "cat: \"%s\" not found" },
    { "cat: Dateiname fehlt",
      "cat: file name missing" },
    { "cd: \"%s\" ist kein Ordner",
      "cd: \"%s\" is not a folder" },
    { "davon %s mehrfach genutzt (Kopie beim Schreiben)",
      "of which %s is shared (copy on write)" },
    { "die ersten Zeilen",
      "the first lines" },
    { "die letzten Zeilen",
      "the last lines" },
    { "die mitgelieferten Programme auflisten",
      "list the bundled programs" },
    { "die zuletzt eingegebenen Zeilen",
      "the lines entered most recently" },
    { "diese Uebersicht",
      "this overview" },
    { "edit: \"%s\" nicht gefunden",
      "edit: \"%s\" not found" },
    { "ein Archiv auspacken",
      "unpack an archive" },
    { "ein Programm eingesperrt starten",
      "start a program in a cage" },
    { "ein Programm in Ring 3 ausfuehren",
      "run a program in ring 3" },
    { "ein laufendes Programm beenden",
      "end a running program" },
    { "eine Weile nichts tun",
      "do nothing for a while" },
    { "einen Monat als Kalender",
      "a month as a calendar" },
    { "finde [pfad] <muster>",
      "find [path] <pattern>" },
    { "finde: \"%s\" nicht gefunden",
      "find: \"%s\" not found" },
    { "firewall regel <eingehend|ausgehend> <erlauben|verwerfen|ablehnen> <alle|tcp|udp|icmp> <alle|adresse[/bits]> <alle|port[-port]>",
      "firewall regel <eingehend|ausgehend> <erlauben|verwerfen|ablehnen> <alle|tcp|udp|icmp> <alle|address[/bits]> <alle|port[-port]>" },
    { "firewall standard eingehend|ausgehend erlauben|verwerfen|ablehnen",
      "firewall standard eingehend|ausgehend erlauben|verwerfen|ablehnen" },
    { "fragt RetroOS beim Start nach Name und Passwort.",
      "RetroOS asks for a name and password at startup." },
    { "ganze Zahlen ausrechnen",
      "work out whole numbers" },
    { "gelaufen",
      "finished" },
    { "gemeldet",
      "answered" },
    { "gepackt",
      "packed" },
    { "groesse: \"%s\" nicht gefunden",
      "du: \"%s\" not found" },
    { "haengt am Ende",
      "following the end" },
    { "hat geantwortet",
      "answered" },
    { "hat sich nicht gemeldet",
      "did not answer" },
    { "hineinsehen, ohne auszupacken",
      "look inside without unpacking" },
    { "hoch",
      "high" },
    { "hoch, mittel oder niedrig",
      "high, medium or low" },
    { "holen: %s",
      "holen: %s" },
    { "holen: %s laesst sich nicht anlegen",
      "holen: %s cannot be created" },
    { "holen: %s laesst sich nicht schreiben",
      "holen: %s cannot be written" },
    { "holen: <adresse> [datei]",
      "holen: <address> [file]" },
    { "im Arbeitsspeicher",
      "in memory" },
    { "in den Papierkorb legen",
      "move to the trash" },
    { "in ein ZIP-Archiv packen",
      "pack into a ZIP archive" },
    { "info: \"%s\" nicht gefunden",
      "stat: \"%s\" not found" },
    { "installieren: %s",
      "installieren: %s" },
    { "installieren: %s gibt es nicht",
      "installieren: there is no %s" },
    { "kaefig <profil> <programm> [text]",
      "kaefig <profile> <program> [text]" },
    { "kalender [monat] [jahr]",
      "cal [month] [year]" },
    { "kein Bild",
      "no image" },
    { "keine",
      "none" },
    { "keine (DHCP ohne Antwort)",
      "none (DHCP got no answer)" },
    { "keine Geraete",
      "no devices" },
    { "keine gefunden",
      "none found" },
    { "keines gefunden",
      "none found" },
    { "kopiere <quelle> <ziel>",
      "cp <source> <target>" },
    { "kopiere: \"%s\" gibt es dort schon",
      "cp: \"%s\" is already there" },
    { "kopiere: \"%s\" ist kein Ordner",
      "cp: \"%s\" is not a folder" },
    { "kopiere: \"%s\" nicht gefunden",
      "cp: \"%s\" not found" },
    { "kopiere: das waere eine Kopie in sich selbst",
      "cp: that would be a copy into itself" },
    { "kopiere: es ging nicht - fehlen die Rechte?",
      "cp: it did not work - permissions missing?" },
    { "laeuft",
      "running" },
    { "laufende Programme mit Verwandtschaft",
      "running programs and their kinship" },
    { "laufende Threads mit Zustand und Rechenzeit",
      "running threads with state and CPU time" },
    { "leere Datei anlegen",
      "create an empty file" },
    { "ls: \"%s\" darfst du nicht lesen",
      "ls: you may not read \"%s\"" },
    { "ls: \"%s\" ist eine Datei",
      "ls: \"%s\" is a file" },
    { "ls: \"%s\" nicht gefunden",
      "ls: \"%s\" not found" },
    { "man <befehl>",
      "man <command>" },
    { "mittel",
      "medium" },
    { "mkdir: \"%s\" konnte nicht angelegt werden",
      "mkdir: \"%s\" could not be created" },
    { "mkdir: Name fehlt",
      "mkdir: name missing" },
    { "nicht eingehaengt",
      "not mounted" },
    { "nicht vorhanden",
      "not present" },
    { "niedrig",
      "low" },
    { "normal",
      "normal" },
    { "nur Tastatur - keine Maus an Port 2",
      "keyboard only - no mouse on port 2" },
    { "papierkorb zurueck: Nummer 1 bis %u erwartet",
      "papierkorb zurueck: a number from 1 to %u is expected" },
    { "ping: %s nicht gefunden",
      "ping: %s not found" },
    { "ping: Ziel fehlt",
      "ping: no target given" },
    { "ping: keine Netzwerkverbindung",
      "ping: no network connection" },
    { "protokoll [alle|warnung|fehler|speichern|leeren]",
      "protokoll [alle|warnung|fehler|speichern|leeren]" },
    { "rechne <ausdruck>",
      "expr <expression>" },
    { "rechne: %s",
      "expr: %s" },
    { "rechte: \"%s\" nicht gefunden",
      "rechte: \"%s\" not found" },
    { "rechte: \"750\" oder \"rwxr-x---\" wird erwartet",
      "rechte: \"750\" or \"rwxr-x---\" is expected" },
    { "rm: \"%s\" ist geschuetzt",
      "rm: \"%s\" is protected" },
    { "rm: \"%s\" nicht gefunden",
      "rm: \"%s\" not found" },
    { "roh",
      "stored" },
    { "schlaeft",
      "sleeping" },
    { "schreib: \"%s\" darfst du nicht beschreiben",
      "schreib: you may not write to \"%s\"" },
    { "schreib: \"%s\" ist ein Ordner",
      "schreib: \"%s\" is a folder" },
    { "schreib: \"%s\" laesst sich nicht anlegen - fehlen die Rechte?",
      "schreib: \"%s\" cannot be created - permissions missing?" },
    { "schreib: <datei> <text>",
      "schreib: <file> <text>" },
    { "sortiere: hoechstens 200 Zeilen",
      "sort: 200 lines at most" },
    { "sortiere: kein Speicher",
      "sort: out of memory" },
    { "starte: %s",
      "starte: %s" },
    { "starte: <programm> [text]",
      "starte: <program> [text]" },
    { "stumm",
      "silent" },
    { "suche <text> [pfad]",
      "grep <text> [path]" },
    { "suche: \"%s\" nicht gefunden",
      "grep: \"%s\" not found" },
    { "tot",
      "dead" },
    { "touch: \"%s\" existiert bereits",
      "touch: \"%s\" already exists" },
    { "touch: Name fehlt",
      "touch: name missing" },
    { "umbenannt in %s",
      "renamed to %s" },
    { "unbekannt",
      "unknown" },
    { "ungespeichert",
      "unsaved" },
    { "unverschluesselt",
      "unencrypted" },
    { "vergleiche: kein Speicher",
      "diff: out of memory" },
    { "verschiebe <quelle> <ziel>",
      "mv <source> <target>" },
    { "verschiebe: \"%s\" gibt es dort schon",
      "mv: \"%s\" is already there" },
    { "verschiebe: \"%s\" gibt es nicht",
      "mv: there is no \"%s\"" },
    { "verschiebe: \"%s\" gibt es schon",
      "mv: \"%s\" already exists" },
    { "verschiebe: \"%s\" nicht gefunden",
      "mv: \"%s\" not found" },
    { "verschiebe: das Kopieren scheiterte",
      "mv: the copy failed" },
    { "verschiebe: das Umbenennen ging nicht",
      "mv: the rename did not work" },
    { "verschiebe: es ging nicht",
      "mv: it did not work" },
    { "verschiebe: kopiert, aber das Original blieb",
      "mv: copied, but the original stayed" },
    { "verschieben oder umbenennen",
      "move or rename" },
    { "verschoben nach %s",
      "moved to %s" },
    { "vollstaendig neu geschrieben:",
      "written entirely from scratch:" },
    { "warte <millisekunden>",
      "sleep <milliseconds>" },
    { "wartet",
      "waiting" },
    { "wie ueber BIOS.",
      "as well as BIOS." },
    { "wo <name>",
      "which <name>" },
    { "wo ein Programm liegt",
      "where a program comes from" },
    { "zwei Dateien vergleichen",
      "compare two files" },
};

const size_t lang_table_count = ARRAY_LEN(lang_table);
